### ISSUE TITLE
 Improve Markdown List Alignment

### ISSUE THREAD

**Issue by Nadai2010** [Scaffold-Stark/speedrunstark#128]
## Issue Overview

The `page.tsx` component currently displays Markdown lists (`ul` and `ol`) with improper alignment compared to other Markdown elements, such as headers and paragraphs. This misalignment causes visual inconsistency and affects the readability of the content. The issue is particularly noticeable on smaller screens or devices where the extra indentation stands out more prominently.

- Lists (`ul`, `ol`, `li`) appear overly indented compared to headers and paragraphs.
- Visual inconsistency detracts from the overall readability and presentation of Markdown content.

![imagen](https://github.com/user-attachments/assets/51cc7679-7e04-4be4-8d07-972aca8dabbb)
![imagen](https://github.com/user-attachments/assets/2b284cf4-4d55-4a23-bde5-b01ea3abbe73)

**Features Required:**

- Update styling for Markdown list elements to ensure consistent alignment with other Markdown elements.
- Test changes across different devices and screen sizes to maintain responsiveness and readability.

## **Proposed Solutions or Ideas**

**Solution:**

1. **Update the `getMarkdownComponents` Function:**
   - Modify the `getMarkdownComponents` function to apply custom CSS styles to the `ul`, `ol`, and `li` elements.
   - Set consistent `padding` and `margin` values to align lists properly with headers and paragraphs.

2. **CSS Adjustments:**
   - Add specific classes to handle the alignment of lists and list items, such as `pl-5` for padding on the left and `ml-0` to remove unnecessary margins.
   - Ensure that list items (`li`) have minimal left margin (`ml-2`) to balance the spacing.

![imagen](https://github.com/user-attachments/assets/1f13a15d-bc8d-47bb-b444-f15fe17d234b)
![imagen](https://github.com/user-attachments/assets/141718da-6130-458d-b9b8-a14940df4014)

**Comment by Gift-Naomi** [comment]
@Nadai2010 can I work on this?

**Comment by Nadai2010** [comment]
Hi @Gift-Naomi this issue was an internal to be located, the solution has already been uploaded.

Thanks for wanting to contribute.

**Comment by Gift-Naomi** [comment]
> Hi @Gift-Naomi this issue was an internal to be located, the solution has already been uploaded.
> 
> Thanks for wanting to contribute.

Okay sir
I’ll like to contribute if there are any more of issues.
