### ISSUE TITLE
Wrong Eth Balance Display

### ISSUE THREAD

**Issue by tekkac** [Scaffold-Stark/speedrunstark#137]
## Issue Overview

  The Eth balance display is wrong because of incorrect padding.

## Proposed Solutions or Ideas

Correct the off-by-one error in the balance computation.

![screen2](https://github.com/user-attachments/assets/e01a1b85-8ab0-4861-ad72-66ed198805ce)
![screen1](https://github.com/user-attachments/assets/ec81e0b6-8b70-45d0-ba94-29f6f0ed6c16)

**Comment by Nadai2010** [comment]
Hi, thanks for the contribution.

What is the process to detect the issue? I attach tests in Braavos and Argent, sorry for the quality of the images, but if I took a screenshot the values ​​in the wallets looked blurry.

![1(1)](https://github.com/user-attachments/assets/a6e1520c-710c-40bd-ad70-3d9ae5bd61ac)

![2(3)](https://github.com/user-attachments/assets/064517ec-9bec-4e45-b522-3b1e17d0057c)

**Comment by tekkac** [comment]
You should try on the [speedrunstark website](https://speedrunstark.com/).
The issue doesn't occur in the original scaffold-stark repo as the hook is different.

**Comment by Nadai2010** [comment]
Ah perfect, thank you very much,🫡
