### ISSUE TITLE
Challenge 0: Duplicate Metadata NFT

### ISSUE THREAD

**Issue by Nadai2010** [Scaffold-Stark/speedrunstark#141]
## Issue Overview

In the branch `challenge-0-simple-nft`. When minting is done very quickly on `Sepolia`, a NFT may get duplicated. So far, this behavior has been observed with Token ID 1. It appears that the issue could be related to either the `addToIPFS` or `getMetadataFromIPFS` functions. One of these processes might not have enough time to update or retrieve the correct metadata, resulting in the same token (in this case, ID 1) being added multiple times.

![Screenshot from 2024-09-06 20-51-22](https://github.com/user-attachments/assets/f48b9708-31ff-4ac8-9cb7-d9cfd04012c8)

[Sepolia Smart Contract with issue](https://sepolia.starkscan.co/nft-contract/0x01bf3332fd4146d242c05c192880c4d37f58a125196bde07d86b3559c7b0a6de)

This issue is not observed when the contract is deployed on devnet

## Proposed Solutions or Ideas

One possible idea is to implement a delay or retry mechanism within the `addToIPFS` and `getMetadataFromIPFS` processes to ensure that the metadata is properly updated and retrieved before proceeding with the minting process.

### Instructions for Contributing

- Leave a comment on this Issue.
- Wait for our confirmation to start. **Team will assign a participant after september 11th**
- Once you have received confirmation, begin working on your contribution.

### Incentives

Contributions are rewarded via Only Dust.

### Contact

For questions, join to our [tg group](https://t.me/+wO3PtlRAreo4MDI9) and reach out our team

**Comment by Immanuelolivia1** [comment]
i

**Comment by gianalarcon** [comment]
After speedrun campaing finish, the team will assign this issue

welcome to join to the campaign https://github.com/Scaffold-Stark/speedrunstark/issues/139

**Comment by ShantelPeters** [comment]
Hi @gianalarcon  can i please work on this

**Comment by gianalarcon** [comment]
Hi @ShantelPeters. Thanks for showing your interest.

After speedrun campaing finish, the team will assign this issue

**WELCOME TO JOIN THE CAMPAIGN  https://github.com/Scaffold-Stark/speedrunstark/issues/139**

**Comment by ShantelPeters** [comment]
Alright then I’ll be looking forward to contributing.

**Comment by Nadai2010** [comment]
Hello everyone,  @JoE11-y  the Issues for the OD Hack will be assigned to each of you at the start, prepare your skills.

**Comment by MPSxDev** [comment]
Hello, I am Manuel, a process engineer and web3 developer. I have participated in Starknet Bootcamps, ETHGlobal  and am an Elite winner of Speedrunstark. I have a high capacity to solve problems. I am a member of the DojoCoding community.
I hope this issue is assigned to me. I am available to work immediately to achieve what is required in the shortest time possible.

**Comment by metalboyrick** [comment]
all yours @ShantelPeters, all the best!

**Comment by ShantelPeters** [comment]
@metalboyrick  thank you sir 🚀

**Comment by Nadai2010** [comment]
Hey @ShantelPeters , any updates on this issue?

**Comment by ShantelPeters** [comment]
@Nadai2010 Yes .. I will create a PR soon .
