### ISSUE TITLE
Full update challenge 0 based on new challenge-base branch.

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/speedrunstark#145]
## Issue Overview

Update the `challenge-0-simple-nft` branch in accordance to `base-challenge-template` branch. This `base-challenge-template` has the new features of [scaffold-stark-2](https://github.com/Scaffold-Stark/scaffold-stark-2)

**NOTE: PLEASE WAIT FOR #144 TO BE RESOLVED FIRST**

## Proposed Solutions or Ideas

- Update the `challenge-0-simple-nft` branch based on `base-challenge-template`
- Remove mock contracts if not need it
- Resolve any breaking changes
- Improve the smart contract and Cairo tests(snfoundry 0.30.0) to use latest features of cairo 2.8.2 and Openzeppelin 0.17.0

**Comment by ShantelPeters** [comment]
Hi @metalboyrick please i will like to work on this when the hackathon  begins

**Comment by CollinsC1O** [comment]
@metalboyrick i will love to take up on this. I will patiently wait for https://github.com/Scaffold-Stark/speedrunstark/issues/144 to be resolved

**Comment by danielcdz** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hello, I'm Daniel Calderón!
I'm a passionate software engineer with over 3 years of experience, actively contributing to open-source projects through OnlyDust. I’m also a community moderator at Dojo Coding, where I help new developers get started with blockchain development.
Over the past few months, I've contributed to several Starknet projects, including cairo-vm-go by Nethermind. Currently, I’m a Cairo developer at ByteBuilders, working on ByteBeasts, a fully on-chain RPG game built using the Dojo Engine framework.
My expertise spans full-stack development, with a focus on backend, frontend, and smart contract development in blockchain ecosystems.

I recently contributed to this project, to the challenge-0!


### How I plan on tackling this issue
To solve this issue I will do the following:
- Update the base fork branch
- Solve any issue related to dependencies 
- Refactor Cairo smart contracts to match the latest cairo features

I recently contributed to this specific branch `challenge-0` so I already have enough context of the project and what needs to be done, get the work done can take me about 2 days after the issue gets ready to be worked.

**Comment by gianalarcon** [comment]
All yours @danielcdz!

**Comment by danielcdz** [comment]
thank you sir! @gianalarcon

**Comment by danielcdz** [comment]
I'm starting to work on this. since issue #144 is done

**Comment by Nadai2010** [comment]
Hey @danielcdz , any updates on this issue?
