### ISSUE TITLE
Front-end issue on challenge 0

### ISSUE THREAD

**Issue by sandragcarrillo** [Scaffold-Stark/speedrunstark#161]
## Issue Overview

While trying to deploy challenge 0 on vercel, it gave me this error: 

<img width="1171" alt="image" src="https://github.com/user-attachments/assets/7dc96c2a-b788-46ba-99b2-41a34b17689f">

We are currently importing decodeBigIntArrayToText from contractsData, but it doesn't exist on contractsData so it doesn’t let to deploy on vercel due to that error.

`import { decodeBigIntArrayToText } from "~~/utils/scaffold-stark/contractsData";`

I removed that line from MyHoldings.tsx and it worked perfectly 

## Proposed Solutions or Ideas

Just remove that line from MyHoldings.tsx, I tested the dapp without that line and it didn’t have any issue, not even live in Sepolia

**Comment by sandragcarrillo** [comment]
This issue is already fixed with [this PR ](https://github.com/Scaffold-Stark/speedrunstark/pull/160). I would leave my issue just to remind the team to merge the PR to solve it. Sorry for duplicating an issue.

**Comment by jrcarlos2000** [comment]
Thanks for reporting 🙌🏽
