### ISSUE TITLE
[CHORE] Sync New changes from Scaffold Stark to SpeedRun Base Template

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/speedrunstark#171]
## Issue Overview

Keep dependencies in-sync between `scaffold-stark` main repo and `speedrunstark`

## Proposed Solutions or Ideas

- Sync fork in a branch 
- Resolve any merge conflicts and dependency errors
- Run unit tests to make sure they work
- Make sure page runs fine

**Comment by tosoham** [comment]
May I be assigned to this?

**Comment by Supa-mega** [comment]
Could I try solving this?

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by abdegenius** [comment]
I’d love to work on this task.

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi,  

I’d be thrilled to work on this issue as I have extensive experience with Cairo programming and building decentralized applications on StarkNet.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!   

Looking forward to contributing!

**Comment by ShantelPeters** [comment]
Can I tackle this one?

**Comment by Amarjeet325** [comment]
Can I take care of this issue?

**Comment by michojekunle** [comment]
Hi, I’d like to work on this issue syncing dependencies between scaffold-stark main repo and speedrunstark repo. 

### My proposed steps:

**Sync Fork:** Update the fork by creating a branch and syncing it with the latest main repo changes.
**Resolve Conflicts:** Address any merge conflicts and fix dependency-related issues.
**Run Unit Tests:** Ensure all tests pass to maintain functionality and stability.
**Validate Application:** Confirm the pages load and function correctly across the repos.

## ETA: 48 hours

I’ll complete the task efficiently and ensure both repos are aligned without errors. 

Looking forward to your approval to proceed!

**Comment by TheSQLguy** [comment]
To address this issue, I would create a branch in the fork and sync it with the upstream scaffold-stark repo. Solve any merge conflicts and update the dependencies to match speedrunstark. Run unit tests to confirm functionality and that the page loads without an error. Submit the PR for review.

**Comment by metalboyrick** [comment]
conpleted by merge
