### ISSUE TITLE
[FEAT] refactor chaper 0 + integrate features of OZ 0.20.0

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/speedrunstark#172]
## Issue Overview

Refactor the `SimpleNFT.cairo` contract to use OpenZeppelin 0.20.0

## Proposed Solutions or Ideas

- Upgrade OpenZeppelin
- Refactor the NFT contract to ensure no errors are happening
- Test them out

**Comment by manlikeHB** [comment]
Hi, I am a Cairo Developer with great experience contributing to lots of amazing Cairo projects. I am very familiar with embedding component in a contract especially OpenZeppelin contracts. Can I working on this?

**Comment by GideonBature** [comment]
I’d love to work on this task.

Could I be assigned to this?

My name is Gideon Bature, a Software Engineer, I have experience working with Cairo, integrating OpenZeppelin, making sure everything works seamlessly. If given the opportunity, I will send my first PR within 48 hours.

Thank you!

**Comment by jedstroke** [comment]
May I take this issue on?

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi,  

I’d be thrilled to work on this issue as I have extensive experience with Cairo programming and building decentralized applications on StarkNet.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!   

Looking forward to contributing!

**Comment by kayceeDev** [comment]
Can I work on this, please?

**Comment by ShantelPeters** [comment]
Can I attempt this issue?

**Comment by TheSQLguy** [comment]
To solve this issue, I would

Upgrade the project to OpenZeppelin 0.20.0, which is compatible with the SimpleNFT contract.
Refactor the SimpleNFT.cairo contract to match OpenZeppelin's latest standards and features.
Thoroughly test the upgraded contract, thus checking on its functionality and making sure that no errors happen after upgrading.

**Comment by michojekunle** [comment]
Hello, I’d like to work on refactoring the SimpleNFT.cairo contract to use OpenZeppelin 0.20.0. 

My approach:

Upgrade Dependencies: Update the contract to integrate OpenZeppelin 0.20.0.
Refactor Contract: Modify the NFT contract to align with the updated standards while maintaining existing functionality.
Testing: Run thorough tests to ensure the contract works well without introducing errors.
Submit PR: Follow the repository’s contribution guidelines and link the PR to this issue.

### I’ll complete this task within 48 hours and deliver a clean, functional solution.

Looking forward to your approval

**Comment by manlikeHB** [comment]
Hi @metalboyrick @Nadai2010, Can you point me to where the `SimpleNFT.cairo` file is?

**Comment by Nadai2010** [comment]
Hi @manlikeHB, in branch challenge-0, the file is YourCollectible.cairo

https://github.com/Scaffold-Stark/speedrunstark/blob/challenge-0-simple-nft/packages/snfoundry/contracts/src/YourCollectible.cairo
